### ISSUE TITLE
Refactor interchainstaking/keeper/abci.go

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#13]
A lot happens in the blockers; this file is getting long - lets refactor out the meat into functions on the keeper, and leave the modulo logic, the iterators (?) and not much else.

**Comment by levicook** [comment]
Started a draft PR; took a guess on reasonable method names (feedback appreciated)

I also spotted a few places where it seems like loops should `continue` in these iterators that deserve scrutiny. Going to fiddle with tests a bit more to see if they signal something I've got wrong here too.

**Comment by joe-bowman** [comment]
Hey Levi, sorry @zanicar already started on this (there is an open PR, I haven’t merged yet). Will try and get these issues cleaned up tonight to avoid duplication of effort.

**Comment by levicook** [comment]
No worries at all! This was code I was very curious about & wanted to study anyway :)
I'll close the PR tho

**Comment by zanicar** [comment]
Refactor has been merged to main... closing.
