### ISSUE TITLE
x/interchainstaking/keeper: utilize known map size to generate keys slice in (ValidatorIntents).Keys

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#152]
If we look at this code in https://github.com/ingenuity-build/quicksilver/blob/99b1e83ca9c0ede6f54c152a7895870d2ea9c87c/x/interchainstaking/types/delegation.go#L112-L122
we can improve its performance by instead doing the following

```go
 keys := make([]string, 0, len(v)) 
 for key := range v { 
 	keys = append(keys, key) 
 } 
 sort.Strings(keys) 
  
 return keys
```

or even faster

```go
 keys := make([]string, len(v)) 
 i := 0
 for key := range v { 
 	keys[i] = key
        i++
 } 
 sort.Strings(keys) 
  
 return keys
```

and here are some performance studies showing benefits per https://bencher.orijtech.com/perfclinic/sliceupdate and in particular the shoot-out results in https://bencher.orijtech.com/perfclinic/sliceupdate/#results

**Comment by joe-bowman** [comment]
closed by #155
