### ISSUE TITLE
x/interchainstaking/types: simplify and optimize indentString to use strings.Repeat instead of manual string concatenation n times

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#153]
If we look at this code https://github.com/ingenuity-build/quicksilver/blob/99b1e83ca9c0ede6f54c152a7895870d2ea9c87c/x/interchainstaking/types/error.go#L57-L64 , it essentially goes through d times and manually builds a string via concatenation of the indent string but really it can be simplified to just (and improve readability by changing d to n)
```go
 func indentString(indent string, n int) string { 
     return strings.Repeat(indent, n)
}
```

**Comment by joe-bowman** [comment]
closed by #155
