### ISSUE TITLE
x/interchainstaking/keeper: suspicious code in parseDelegationKey

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#181]
The `parseDelegationKey` functions contains a commented out variant of its parsing:

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/ibc_packet_handlers.go#L584-L593

The `valAddrLen` should be removed altogether, or the parsing implementation updated to match reality. In either case, a test should verify that parseDelgationKey really does match the expected format of a delegation key, because it is only called from a special (rare?) case in a callback:

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/callbacks.go#L167-L169

CC @odeke-em

**Comment by joe-bowman** [comment]
`valAddrLen` field was originally ignored, because we can simply read to the end of the slice. But I have added validation and out-of-bounds checking to the method - and caught another bug where I'd used python style [start:length] instead of [start:end] syntax.

Good catch!
