### ISSUE TITLE
x/interchainstaking/keeper: possible unbalanced increment/decrement to Zone.WithdrawalWaitgroup

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#185]
I couldn't find any documentation for [`types.Zone.WithdrawalWaitgroup`](https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/proto/quicksilver/interchainstaking/v1/genesis.proto#L35) in particular none describing the field's invariants. It seems to me that it's a counter field where every increment is balanced with a decrement. I found

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/callbacks.go#L132-L133

with a stale reference to "L93". Supposedly that reference is for

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/hooks.go#L78

In which case the comment should be updated.

However, I failed to find a definitive counterpart for

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/ibc_packet_handlers.go#L711-L715

Maybe it's

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/delegation.go#L236-L237

in which case it should be clearly documented, in particular why there's a `if withdrawalMsg.DelegatorAddress != zone.PerformanceAddress.Address` check for the decrement but apparently not for the increment(s).

CC @odeke-em

**Comment by zanicar** [comment]
Incoming commit has comments added to clearly indicate increment:decrement pairings.

We have two pairs:

1. Query/DelegationTotalRewards (increment on query, decrement on callback);
2. MsgWithdrawDelegatorReward (increment on msg sent for every validator delegated to, decrement in HandleWithdrawRewards on IBC acknowledgement);

`zone.PerformanceAddress` is used to track validator performance and does not operate in the waitgroup set, therefor we must check to exclude it when receiving an acknowledgement.

**Comment by joe-bowman** [comment]
Documented in #221
