### ISSUE TITLE
x/interchainstaking/keeper: possible missing out-of-bounds check in AccountBalanceCallback

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#187]
There's no length check before slicing:

https://github.com/ingenuity-build/quicksilver/blob/a7f142ab99e978482f66248d0009b90820d0f0ce/x/interchainstaking/keeper/callbacks.go#L432

There may be a higher-level reason that `len(request.Query)` is always greater than zero.

CC @odeke-em

**Comment by joe-bowman** [comment]
The value of `query.Request` here is only ever set by `x/interchainstaking/x/keeper/zones.go:SetAccountBalance()` so I am reasonably confident that this is fine as it for now; however, to protect against future untended behaviour from usage with an incorrect `request` key, I've added the requisite protections.
