### ISSUE TITLE
x/interchainstaking/keeper: HandleCompleteMultiSend re-implements handleSendToDelegate

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#197]
`Keeper.HandleCompleteMultiSend` contains a re-implementation of `Keeper.handleSendToDelegate`, here:

https://github.com/ingenuity-build/quicksilver/blob/00a76ee447b614471ef5aded5c70fd88c9fce70a/x/interchainstaking/keeper/ibc_packet_handlers.go#L242-L273

For reference, here's `handleSendToDelegate`:

https://github.com/ingenuity-build/quicksilver/blob/00a76ee447b614471ef5aded5c70fd88c9fce70a/x/interchainstaking/keeper/ibc_packet_handlers.go#L327-L355

It would reduce the attack surface and seems logical to implement multi-sends in term of single-send.

CC @odeke-em

**Comment by joe-bowman** [comment]
Resolved by #221
