### ISSUE TITLE
x/interchainstaking/keeper: prepareRewardsDistributionMsgs ignores rewards denomination

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#199]
`Keeper.prepareRewardsDistributionMsgs` takes a `sdk.Coin` for its `rewards` parameter,

https://github.com/ingenuity-build/quicksilver/blob/00a76ee447b614471ef5aded5c70fd88c9fce70a/x/interchainstaking/keeper/ibc_packet_handlers.go#L827

but the method ignores its denomination and always uses `zone.BaseDenom`. I suggest guarding against misuse by changing the `rewards` parameter type to `sdk.Int`, making it clear that the denomination is ignored. Note that the only caller constructs `sdk.Coin` just for this use:

https://github.com/ingenuity-build/quicksilver/blob/00a76ee447b614471ef5aded5c70fd88c9fce70a/x/interchainstaking/keeper/ibc_packet_handlers.go#L765-L767

EDIT: as additional support, note that the method returns a denomination-free `dust` value.

CC @odeke-em

**Comment by elias-orijtech** [comment]
Same comment applies to `Keeper.updateRedemptionRate`:

https://github.com/ingenuity-build/quicksilver/blob/00a76ee447b614471ef5aded5c70fd88c9fce70a/x/interchainstaking/keeper/ibc_packet_handlers.go#L815

even though the risk of misuse is lower: the calls to `sdk.Coin.Add` panics if there is a denomination mismatch.

**Comment by joe-bowman** [comment]
Resolved in #221
