### ISSUE TITLE
x/interchainstaking/keeper: asset/qAsset ratio computation lacks special-case handling

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#203]
The ratio computation,

https://github.com/ingenuity-build/quicksilver/blob/8c558f01b2b2528bd36c484da2c0b5d64e2b110b/x/interchainstaking/keeper/ibc_packet_handlers.go#L804

assumes that neither the local nor base balance ever reaches zero. It's not clear to me whether that assumption always holds; for example, what happens if everyone burns their qAssets, thus withdrawing all their assets?

Depending on which account reaches zero, the ratio computation will either panic (division by zero) or result in a ratio of zero. A zero ratio is problematic in code such as

https://github.com/ingenuity-build/quicksilver/blob/8c558f01b2b2528bd36c484da2c0b5d64e2b110b/x/interchainstaking/keeper/receipt.go#L110-L112

and is inconsistent with zone proposal initialization where the ratio is 1 even though there are no assets yet:

https://github.com/ingenuity-build/quicksilver/blob/8c558f01b2b2528bd36c484da2c0b5d64e2b110b/x/interchainstaking/keeper/proposal_handler.go#L32

CC @odeke-em

**Comment by joe-bowman** [comment]
Fixed in #221
