### ISSUE TITLE
x/interchainstaking/keeper: undocumented clever code in ApplyDeltasToIntent

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#207]
The re-balance code in ApplyDeltasToIntent,

https://github.com/ingenuity-build/quicksilver/blob/8c558f01b2b2528bd36c484da2c0b5d64e2b110b/x/interchainstaking/keeper/zones.go#L366-L388

apparently has a redundant check in lines 369-371, which warrants a closer look. However the code section is undocumented, and its test,

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/interchainstaking/keeper/zones_test.go#L91-L102

doesn't describe it better (no invariants, no `Error/Fatal` calls).

This issue is about documenting the code, preferably with test(s).

CC @odeke-em

**Comment by joe-bowman** [comment]
This code no longer exists.
