### ISSUE TITLE
x/participationrewards: (types.MsgSubmitClaim) GetSigners() doesn't check that incoming message useraddresses are parseable and catch errors

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#208]
If we look at this code, it receives input from the wild but doesn't check the error when parsing an account address from a message
https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/participationrewards/types/msgs.go#L22

I would be important for security to always parse and handle errors for messages sent in from the wild, because other that blinds builds on trust assuming that all incoming messages will ALWAYS have correct formats but some peers could be malicious

/cc @elias-orijtech

**Comment by zanicar** [comment]
Is this not implicitly done by sdk.Msg (interface) ValidateBasic?

**Comment by joe-bowman** [comment]
Agreed - surely ValidateBasic is called before we ever call GetSigners?

**Comment by joe-bowman** [comment]
Closed; this case is covered by validateBasic()
