### ISSUE TITLE
x/participationrewards: (types.MsgSubmitClaim).ValidateBasic is invalid and always returns nil

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#209]
If we examine this code, it is incomplete and returns nil always

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/participationrewards/types/msgs.go#L27-L38

The fix for this could be to use something like https://github.com/hashicorp/go-multierror to compose errors and then validate that ChainID is valid, that .UserAddress is also good.

/cc @elias-orijtech

**Comment by zanicar** [comment]
Yes, this function is incomplete... fix in upcoming commit.
