### ISSUE TITLE
x/participationrewards: (types.AddProtocolDataProposal).ValidateBasic() is return with multiple returns but could simply be 1 line

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#210]
This code is redundant https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/participationrewards/types/proposals.go#L28-L33 and can be simplified to a single return err per

```go
return govtypes.ValidateAbstract(m)
```

/cc @elias-orijtech

**Comment by joe-bowman** [comment]
resolved by #221
