### ISSUE TITLE
x/participationrewards: (types.Params).Validate() is redundant and can be simplified to just 1 line

### ISSUE THREAD

**Issue by odeke-em** [ingenuity-build/quicksilver#211]
This code https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/participationrewards/types/params.go#L84-L90

can be simplified to just 1 line 
```go
 func (p Params) Validate() error { 
 	return validateDistributionProportions(p.DistributionProportions)
 } 
```

/cc @elias-orijtech

**Comment by joe-bowman** [comment]
Fixed in #221
