### ISSUE TITLE
x/interchainstaking/types: suspicious TODO in MsgRequestRedemption.ValidateBasic

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#217]
A TODO in a validate function is often (but not always) a sign of missing validation:

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/interchainstaking/types/msgs.go#L33

CC @odeke-em

**Comment by elias-orijtech** [comment]
Another in `MsgSignalIntent.ValidateBasic`:

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/interchainstaking/types/msgs.go#L113

**Comment by joe-bowman** [comment]
Resolved in #221
