### ISSUE TITLE
x/interchainstaking/types: brittle use of NewDecFromStr

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#218]
The initialization of `DefaultCommissionRate`,

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/interchainstaking/types/params.go#L17

is needlessly brittle. I suggest using the error-free `sdk.NewDec` constructor, or at least the error-checking `sdk.MustNewDecFromStr` variant.

CC @odeke-em

**Comment by joe-bowman** [comment]
Closed by #221
