### ISSUE TITLE
x/airdrop/keeper: inconsistent claim record validation

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#219]
The claim record validations at

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/airdrop/keeper/claim_record.go#L131-L133

and

https://github.com/ingenuity-build/quicksilver/blob/4ea3aa77d56b674c7189835064fda16f6bebf8da/x/airdrop/keeper/claim_record.go#L176-L178

seems insufficient: why is check for the empty address enough? If non-empty, yet invalid, addresses are ok, why have the check at all?

CC @odeke-em

**Comment by joe-bowman** [comment]
Fixed in #221
