### ISSUE TITLE
x/participationrewards/keepers: missing length check in OsmosisPoolUpdateCallback

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#226]
https://github.com/ingenuity-build/quicksilver/blob/99ccf2a46267441f602cd7d66ca14c840b46fe9b/x/participationrewards/keeper/callbacks.go#L107

panics if `query.Request` length is in the range (1,5), not inclusive (surprisingly (to me), `sdk.BigEndianToUint64` returns `0` if the supplied slice is empty).

Curiously, the first byte (0x02) is ignored by `OsmosisPoolUpdateCallback`. Perhaps its existence should be validated as well.

CC @odeke-em

**Comment by joe-bowman** [comment]
Thanks :) All these query.Request values are set internally by the protocol, so the risk of these being invalid is _lower_ than user input - however, good to ensure they are validated to protect against inadvertent usage.

**Comment by elias-orijtech** [comment]
Ack. I noted them as LOW for the same reason, and you're welcome to close these issues as not worth the extra complexity.

**Comment by joe-bowman** [comment]
It's a minor overhead to add the validation, and might save us from pain later on - keep them coming :) thank you!
