### ISSUE TITLE
x/participationrewards/keeper: suspicious code in getRewardsAllocations

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#227]
The section,

https://github.com/ingenuity-build/quicksilver/blob/99ccf2a46267441f602cd7d66ca14c840b46fe9b/x/participationrewards/keeper/distribution.go#L39-L54

seems to create a snapshot of intents whenever the module balance reaches zero. But why is the module balance and intent snapshotting related? Note that the TODO and the inner-most comment seem to support my suspicion. 

CC @odeke-em

**Comment by zanicar** [comment]
@elias-orijtech yes, this had me scratching my head... result of a number of refactors and updates over a longer period of time and warrants explanation:

- this is a bootstrapping operation to ensure intent snapshot is available at the epoch boundary for `calcUserValidatorSelectionAllocations`
- there will be no module balance at the end of the first epoch as inflationary emissions is only allocated at this point;
- however, we want to be able to take a snapshot of intents for the next epoch boundary;
- so we check for a zero module balance and for set intents;
- then we take the snapshot;

However, we recently introduced deferred participation rewards for the first couple of epochs, making the above irrelevant.
Snapshots are now taken at epoch boundary during this deferral process, then once participation rewards activate operations the snapshots will be taken during the callback;

**Comment by joe-bowman** [comment]
This looks good to me, yes. The first epoch boundary will see snapshots taken + aggregateIntents set.

**Comment by joe-bowman** [comment]
resolved in #225
