### ISSUE TITLE
x/participationrewards/keeper: token value calculation is incomplete

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#228]
The token value for for zone rewards is stubbed out:

https://github.com/ingenuity-build/quicksilver/blob/99ccf2a46267441f602cd7d66ca14c840b46fe9b/x/participationrewards/keeper/hooks.go#L22-L43

marking this issue as LOW, because the stubbed implementation may very well be adequate for initial release.

CC @odeke-em

**Comment by joe-bowman** [comment]
This has been closed in development.
