### ISSUE TITLE
x/participationrewards/keeper: incomplete basic validation in SubmitClaim

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#229]
The comment in

https://github.com/ingenuity-build/quicksilver/blob/99ccf2a46267441f602cd7d66ca14c840b46fe9b/x/participationrewards/keeper/msg_server.go#L28

refers to "validate basic", but I'm unable to locate that reference in the `SubmitClaim` method or in the 3 callers.

CC @odeke-em

**Comment by elias-orijtech** [comment]
Other than the equal-length check, the other fields of `msg` should be validated: `Zone`, `UserAddress` and possibly `ProofType` and `ProofOps`.

**Comment by elias-orijtech** [comment]
Ok, `ValidateBasic` is [here](https://github.com/ingenuity-build/quicksilver/blob/99ccf2a46267441f602cd7d66ca14c840b46fe9b/x/participationrewards/types/msgs.go#L28), but doesn't contain code to verify equal lengths, nor whether all `ProofOps` are non-nil.

**Comment by zanicar** [comment]
@Joe should we update this to use a Proof type, such as in airdrop?

**Comment by joe-bowman** [comment]
Yes, this would be good. Thank you @zanicar
