### ISSUE TITLE
x/participationrewards/types: incomplete protocol data validation in ValidateGenesis

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#232]
The code and TODO agree that validation is missing for the genesis state data:

https://github.com/ingenuity-build/quicksilver/blob/084e93c1689ccfcc06f1a89452239628d918d6ec/x/participationrewards/types/genesis.go#L41-L50

CC @odeke-em

**Comment by joe-bowman** [comment]
This won't be used in genesis; but will need fixing if we ever need to restore from genesis.

**Comment by joe-bowman** [comment]
This was done a while back, and has been improved in v1.4.x
