### ISSUE TITLE
x/interchainstaking/keeper: TestDeltasAndIntent doesn't test

### ISSUE THREAD

**Issue by elias-orijtech** [ingenuity-build/quicksilver#255]
From the listing:

https://github.com/ingenuity-build/quicksilver/blob/cd20a9a9e9b3aeb146e93822894a6405ac14955f/x/interchainstaking/keeper/zones_test.go#L249-L260

there is no code that can fail the test (except for panics).

CC @odeke-em

**Comment by elias-orijtech** [comment]
Same comment applies to at least some tests in x/interchainstaking/types:

https://github.com/ingenuity-build/quicksilver/blob/cd20a9a9e9b3aeb146e93822894a6405ac14955f/x/interchainstaking/types/delegation_test.go#L13-L26

perhaps these merely test for the absence of panics, but if so a comment should note that.

**Comment by joe-bowman** [comment]
Allocations has been removed in the next lot of changes.

**Comment by joe-bowman** [comment]
Allocation was removed.
