### ISSUE TITLE
Add Deposit account query

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#3]
As a: user
I want: To be able to submit a query for the deposit account for a given chain_id
So that: I am able to determine where to send my tokens for onboarding

---
Acceptance criteria:
- [x] I can submit a query to GRPC to query for deposit account
- [x] I can submit a query via REST to query for deposit account
- [x] Tests

**Comment by joe-bowman** [comment]
This issue will be very similar to the query added in #4 - but return zone.DepositAccount.Address.

**Comment by levicook** [comment]
This appears to be implemented (if I'm following the issue correctly).

Found the query messages here:
https://github.com/ingenuity-build/quicksilver/blob/main/proto/quicksilver/interchainstaking/v1/query.proto#L21-L25

And the implementation here:
https://github.com/ingenuity-build/quicksilver/blob/main/x/interchainstaking/keeper/grpc_query.go#L47-L64

Both seemed reasonable and complete.

**Comment by levicook** [comment]
Oh, seeing this is maybe open because it wants tests still...

**Comment by joe-bowman** [comment]
```
joe@desktop:~/code/quicksilver$ ./build/quicksilverd q interchainstaking deposit-account qscosmos-1
deposit_account_address: cosmos13xdqp22gqlfnfg99pk7t0yz7067x556mpplsj6uemjr7je7zdupqyz8x0y
```

Confirmed working on testnet.

@zanicar is this still waiting on test framework stuff, or closable?

**Comment by zanicar** [comment]
closing
