### ISSUE TITLE
DelegatorIntent should be a map indexed by delegatorAddress

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#30]
Presently, `zone.DelegatorIntent` is a slice of `DelegatorIntent` structs. As each delegator may only have a single intent per zone, this should be a map, indexed by delegator address.

**Comment by levicook** [comment]
If I'm following the intention, this appears to be done:
https://github.com/ingenuity-build/quicksilver/blob/main/proto/quicksilver/interchainstaking/v1/genesis.proto#L24
https://github.com/ingenuity-build/quicksilver/blob/main/x/interchainstaking/types/genesis.pb.go#L39

**Comment by zanicar** [comment]
Indeed, it has been resolved with: Reward withdrawals #33
