### ISSUE TITLE
Handle Error in `participationrewards` `AfterEpochEnd`

### ISSUE THREAD

**Issue by aljo242** [ingenuity-build/quicksilver#343]
We have this [error check](https://github.com/ingenuity-build/quicksilver/blob/7d5d28b0c1940b72ed3c4604df3f723bda83a9a5/x/participationrewards/keeper/hooks.go#L58) in our function that will verify if the error is `types.ErrNothingToAllocate`, but for both branches of the `if` statement, the same logic is called.

The return signature of `GetRewardsAllocations` is `(*RewardsAllocation, error) `, so whenever there is an error, the `RewardsAllocation` is returned as a nil pointer.

Later in the function at [this line](https://github.com/ingenuity-build/quicksilver/blob/7d5d28b0c1940b72ed3c4604df3f723bda83a9a5/x/participationrewards/keeper/hooks.go#L94), we dereference the pointer, so we panic when it is nil. 

We should handle the case where there is an error by returning early or recovering so that this panic does not happen

**Comment by joe-bowman** [comment]
Ah, this was fixed in v1.2.3, but that was after v1.4.0 was forked off; the change needs making to v1.4 also.
