### ISSUE TITLE
upgrade issue

### ISSUE THREAD

**Issue by Huginntech** [ingenuity-build/quicksilver#441]
I am having a problem with my archive node and wanted to consult you. With the v1.2.12 version, I reached block 2149250 and  I got this error: 

`ERR Stopping peer for error err="blockchainReactor validation error: wrong Block.Header.AppHash.  Expected 38CFA6C6D558ECF1A31DC333F4BD3E3E26DAB796150947250B3A32B4DBA678B9, got D3E3DB5DDF2C07ECAF604102E8ED20830B47BF3D405F0FEA05FCA93C75B950D9`

I still get the same error when update to v1.2.13. 
I only use seeds node for p2p. go version is 1.19, commit:  **59f536ae51b2b63446ca43a5610442ba19d123c4**

When I do a quicksilverd rollback and come to back this block 2149249 (with 1.2.13), I get this
```
INF ABCI Handshake App Info hash="��#=C\r\t\x1a\a$�\x11���Isۖ�P7�k��+Yy3o\r" height=2149249 module=consensus protocol-version=0 software-version=v1.2.13
May 31 21:09:33 alayinaarchive quicksilverd[472059]: 9:09PM INF ABCI Replay Blocks appHeight=2149249 module=consensus stateHeight=2149249 storeHeight=2149250
May 31 21:09:33 alayinaarchive quicksilverd[472059]: 9:09PM INF Replay last block using real app module=consensus
May 31 21:09:33 alayinaarchive quicksilverd[472059]: panic: capabilities/ports/icacontroller-cosmoshub-4.delegate/channels/channel-61: capability not found
```

2149249 it continues with 1.2.12;  but I am facing the `**wrong Block.Header.AppHash**` error again at block 2149250

do you have any advice? thanks! https://archive-rpc-quicksilver.huginn.tech/status?

**Comment by joe-bowman** [comment]
This is not unexpected; you need to follow the emergency upgrade path (halt at 2148750 and upgrade) as per the discord and email alerts.

You need to resync from a snapshot or statesync.

**Comment by Huginntech** [comment]
Thanks, archive node was overlooked.

Since I can't use snapshot and state-sync for archive node, I will sync from the first block.
