### ISSUE TITLE
Onboarding qAssets should be calculated using `last_redemption_rate`

### ISSUE THREAD

**Issue by joe-bowman** [ingenuity-build/quicksilver#61]
In order to circumvent potential attack described here: https://discord.com/channels/939972129699561472/939973146558218291/960210775182561320

We should mint new qAssets at the `min()` of the current `redemption_rate` and the `redemption_rate` of the previous epoch (held in `RegisteredZone.LastRedemptionRate` - see #60). For long term qAsset holders, this should be a negligible impact, but serves to penalises users who enter and then immediately exit the protocol.

**Comment by zanicar** [comment]
Should it not mint qAssets at the current `redemption_rate` and burn the `min()` of the `redemption_rate` and the `last_redemption_rate`?

Meaning users will enter the protocol at the current rate and exit at the lesser of the current and previous rate... thereby preventing epoch boundary gaming, even in the event of slashing.

**Comment by joe-bowman** [comment]
Yes, you are correct

**Comment by joe-bowman** [comment]
partially closed by #64; blocked on WithdrawalAccount+FeeAccount piece.

**Comment by joe-bowman** [comment]
closed by #70
