### ISSUE TITLE
Implement qAsset Holdings Allocations

### ISSUE THREAD

**Issue by zanicar** [ingenuity-build/quicksilver#87]
Calculate qAsset holdings scores and allocations:

1. Obtain qAssets pool total value (via Interchain Query to relevant zone);
2. Obtain qAssets held locally by account + sum of claims (or PoP - Proof of Participation);
3. Calculate proportion held (cap at 2%);
4. Normalize and distribute allocation;

This occurs at end of each epoch;
Implement in Keeper (`rewards_holdings.go`);
Call in `hooks.go` -> `AfterEpochEnd`;

**Comment by zanicar** [comment]
Currently blocked on ICQ (Interchain Queries);

**Comment by joe-bowman** [comment]
This has been closed in development.
